### ISSUE TITLE
描述稍微有点问题：“ipa包没有打，打了没有越狱一般也安装不了的，苹果这套对开发者不是很友好”

### ISSUE THREAD

**Issue by madordie** [bravekingzhang/flutter_me#1]
- ipa包不越狱只需要拿企业证书、公司证书、个人证书中的一个进行签名即可正常安装
- 苹果对非付费用户在Xcode7时候已经开启了只要在Xcode中登录iCloud就可以build进真机的调试方案

**Comment by bravekingzhang** [comment]
是这样子么，我有空试试，多谢提醒。
